### ISSUE TITLE
hellow 

### ISSUE THREAD

**Issue by bestdsl** [rmsubekti/emping#1]
I use your emping ,but I have some problem, in _posts filder ,I have three article，so in mainpage should show three article，but in my main page only show one article。You can see the picture with The URl(http://ac-l1vX02tC.clouddn.com/32763884c73603e8276e.png),in the index.html
 , I write 

> ## 🚀 iOS随手记(二)
> 在开发中的总结(二)：{% for post in site.posts limit: 1 %}<a href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>{% endfor %}
> 
> ---
> 
> ## 🅿️ iOS简单沙盒处理
> 针对沙盒的一些简单处理,顺便做了个简单总结：{% for post in site.posts limit: 1 %}<a href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>{% endfor %}
> 
> ## 🅿️ iOS随手记(一)
> 在开发中的总结(一)：{% for post in site.posts limit: 1 %}<a href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>{% endfor %}
> 

i don't know the problem is where,i hope you to help me .

**Comment by rmsubekti** [comment]
hi @bestdsl, thanks for your contribution.
if you want to show more than one article in your main index page (_pages/index.md ). please increase the limit amount  to number of articles you want to show.

```
{% for post in site.posts limit: 1 %}
```


for example

```
{% for post in site.posts limit: 3 %}
```

**Comment by bestdsl** [comment]
no ，no，I don‘t show more article ，I only need one to one, click a heading to get into my articles, and not only an article title, is one to one correspondence.Now I have, for example -- there are three articles respectively under the _posts file is A, B, C, and I also need to display on the home page of the three title respectively is a, b, c, such as the first is the title a, I click on the title a it must enter my article A, I will have to click on the title b into my article B, the same will have to enter, etc., rather than A title A shows A, B, C three article, your reply is a restricted under the heading there are few articles, I want to show one.Don't know whether you understand what I mean.Thank you very much

**Comment by rmsubekti** [comment]
i see, maybe this snippet can help

```
{% for post in site.posts %}
       <h2>
          <a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
        </h2>
          <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>
        <p class="description">
            {% if post.description %}
                {{ post.description | strip_html | strip_newlines | truncate: 250 }}
            {% else %}
                {{ post.content | strip_html | strip_newlines | truncate: 250 }}
            {% endif %}</p>
{% endfor %}
```

for more information about writing post, please go here https://jekyllrb.com/docs/posts/
if you want to show emoji for every post, then you need to customize the [**YAML Front Matter**](https://jekyllrb.com/docs/frontmatter/)  on every post, also change the above liquid template, for example:

```
{% for post in site.posts %}
       <h2>
          {% if post.tag == 'a' %}🚀{% elseif post.tag == 'b' %}🅿️ {% else %}🎵{% endif %}
          <a class="post-link" href="{{ post.url | prepend: site.baseurl }}">{{ post.title }}</a>
        </h2>
          <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>
        <p class="description">
            {% if post.description %}
                {{ post.description | strip_html | strip_newlines | truncate: 250 }}
            {% else %}
                {{ post.content | strip_html | strip_newlines | truncate: 250 }}
            {% endif %}</p>
{% endfor %}
```
