### ISSUE TITLE
How do I set the blog subpath to something that isn't "emping"

### ISSUE THREAD

**Issue by benjamemes** [rmsubekti/emping#2]
Hi,
I set the site subpath to "/" in config.yml yet when I click "Blog", It goes to "/emping/blog/" 👎 
How do I change that?
links: https://github.com/Meme-and-Co/memeandco/blob/master/_config.yml
https://meme-and-co.github.io/memeandco/
Thanks, Ben

**Comment by rmsubekti** [comment]
please you change url and baseurl, to be like this.
```
baseurl: "/memeandco" # the subpath of your site, e.g. /blog
url: "https://meme-and-co.github.io" # the base hostname & protocol for your site
```
if a blog link still point to "/emping/blog", clear the cache or move to another browser to test your site.
it's because this theme also using service worker to serve your site when you offline.

**Comment by benjamemes** [comment]
That worked, Thanks 😄
