### ISSUE TITLE
I can not upload image in the 'about' page.

### ISSUE THREAD

**Issue by Mysigyeong** [rmsubekti/emping#6]
I modified the about.md in _pages directory to change about page.
The problem is the page does not show me images.
I wrote

'
a
![image_name](imageLink)
b
'

like this, in about.md.

but, in the about page, the page just print

'
a
b
'

without image.

Please, give me an answer.

**Comment by aferios** [comment]
Extremely late but I found a temporary fix. Just insert your images in the .md file as if you would in an html file.  e.g.
```<image src="url" width="5cm" height="5cm">``` or ```![comment](url){:height="5cm" width="5cm"}```
Although it will never format to whatever image size you want. I don't know much about SCSS so I don't know how to fix this. But the page element states it is an amp image source. My guess is if amp is disabled then it's golden but I don't know how to do that without breaking the formatting.

**Comment by rmsubekti** [comment]
yes, im sorry.
